//
//  Bundle+CoasterDataManagerResources.swift
//  Copyright © 2025 Jason Fieldman.
//

import Foundation

// This file is autogenerated by Velocity to provide a way to programmatically
// access this Bundle

public extension Bundle {
    /// Access the CoasterDataManagerResources bundle
    static let CoasterDataManagerResources = Bundle(for: CoasterDataManagerResourcesBeacon.self)
    private class CoasterDataManagerResourcesBeacon {}
}
