//
//  Bundle+ResourceExtension.swift
//  Copyright © 2025 Jason Fieldman.
//

import Foundation

// This file is autogenerated by Velocity to provide a way to programmatically
// access this Bundle

public extension Bundle {
    /// Access the ColorsResources bundle
    static let ColorsResources = Bundle(for: ColorsResourcesBeacon.self)
    private class ColorsResourcesBeacon {}
}
