//
//  Colors.swift
//  Copyright © 2025 Jason Fieldman.
//

import UIKit

// This file is autogenerated by Velocity to provide a way to programmatically
// access this Bundle's assets

public extension UIColor {
    enum Colors {
        public static let foregroundSecondary: UIColor = .init(resource: .foregroundSecondary)
        public static let background: UIColor = .init(resource: .background)
        public static let foreground: UIColor = .init(resource: .foreground)
        public static let backgroundSecondary: UIColor = .init(resource: .backgroundSecondary)
    }
}
