//
//  GenerateResources.swift
//  Copyright © 2025 Jason Fieldman.
//

import ArgumentParser
import DependencyMagnetLib
import Foundation
import InternalUtilities
import ModuleManagementLib
import ProjectSpec
import XcodeProj
import Yams

public struct GenerateResourcesOptions {
    public let modulesPath: String
    public let packageFileName: String

    public init(
        modulesPath: String,
        packageFileName: String
    ) {
        self.modulesPath = modulesPath
        self.packageFileName = packageFileName
    }
}

public enum GenerateResources {
    public static func execute(with options: GenerateResourcesOptions) throws {
        let absoluteModuleBasePath = options.modulesPath.prependingCurrentDirectory()
        let absoluteProjectPath = FileManager.default.currentDirectoryPath

        // Verify root path exists
        guard FileManager.default.directoryExists(atPath: absoluteModuleBasePath) else {
            try throwError(.pathNotFound, "Module directory not found at path: \(options.modulesPath)")
        }

        let packages = ModulePackageManager.packages(
            named: options.packageFileName,
            root: options.modulesPath,
            absoluteProjectPath: absoluteProjectPath
        )

        guard packages.count > 0 else {
            vprint(.normal, "No packages found at root path: \(options.modulesPath)")
            return
        }

        // Parse injections
        for package in packages {
            guard let resourceModule = package.modules[.resources] else {
                continue
            }

            try resourceModule.generateBundleExtension()
            try resourceModule.generateAssetExtensions()
        }
    }
}

private extension Module {
    func generateBundleExtension() throws {
        let bundleResourceExtensionPath = projectBasePath.appendingMissingSlash() + "Bundle+\(name).swift"

        // Create bundle extension for resource-containing modules
        try Module.bundleResourceExtensionTemplate
            .replacingOccurrences(of: "{MODULE_NAME}", with: name)
            .write(toFile: bundleResourceExtensionPath, atomically: true, encoding: .utf8)
    }

    private static let bundleResourceExtensionTemplate = """
    import Foundation

    // This file is autogenerated by Velocity to provide a way to programmatically
    // access this Bundle

    public extension Bundle {
        /// Access the {MODULE_NAME} bundle 
        static let {MODULE_NAME} = Bundle(for: {MODULE_NAME}Beacon.self)
        private class {MODULE_NAME}Beacon {}
    }
    """
}

private extension Module {
    func generateAssetExtensions() throws {
        try FileManager.default.files(at: projectBasePath, matching: { $0.hasSuffix(".xcassets") }).forEach { xcassetsPath in
            let assetPackName = xcassetsPath.lastPathComponent.removingSuffix(".xcassets")

            let colorSets = FileManager.default.files(at: xcassetsPath, matching: { $0.hasSuffix(".colorset") })
                .map { $0.lastPathComponent.removingSuffix(".colorset") }

            let imageSets = FileManager.default.files(at: xcassetsPath, matching: { $0.hasSuffix(".imageset") })
                .map { $0.lastPathComponent.removingSuffix(".imageset") }

            guard colorSets.count > 0 || imageSets.count > 0 else {
                return
            }

            var colorTemplateContent = ""
            if colorSets.count > 0 {
                colorTemplateContent = Module.resourceAssetColorExtensionTemplate
                    .replacingOccurrences(of: "{EXT_NAME}", with: assetPackName)
                    .replacingOccurrences(
                        of: "{COLOR_GETTERS}",
                        with: colorSets.map {
                            Module.resourceAssetColorGetterTemplate
                                .replacingOccurrences(of: "{VAR_NAME}", with: $0.lowercaseFirstLetter())
                        }.joined(separator: "\n")
                    )
            }

            var imageTemplateContent = ""
            if imageSets.count > 0 {
                imageTemplateContent = Module.resourceAssetImageExtensionTemplate
                    .replacingOccurrences(of: "{EXT_NAME}", with: assetPackName)
                    .replacingOccurrences(
                        of: "{IMAGE_GETTERS}",
                        with: imageSets.map {
                            Module.resourceAssetImageGetterTemplate
                                .replacingOccurrences(of: "{VAR_NAME}", with: $0.lowercaseFirstLetter())
                        }.joined(separator: "\n")
                    )
            }

            try Module.resourceAssetExtensionTemplate
                .replacingOccurrences(of: "{UICOLOR_EXT}", with: colorTemplateContent)
                .replacingOccurrences(of: "{UIIMAGE_EXT}", with: imageTemplateContent)
                .write(toFile: projectBasePath.appendingMissingSlash() + "\(assetPackName).swift", atomically: true, encoding: .utf8)
        }
    }

    private static let resourceAssetExtensionTemplate = """
    import UIKit

    // This file is autogenerated by Velocity to provide a way to programmatically
    // access this Bundle's assets

    {UIIMAGE_EXT}

    {UICOLOR_EXT}
    """

    private static let resourceAssetImageExtensionTemplate = """
    public extension UIImage {
        enum {EXT_NAME} {
            {IMAGE_GETTERS}
        }
    }            
    """

    private static let resourceAssetImageGetterTemplate = """
    public static let {VAR_NAME}: UIImage = .init(resource: .{VAR_NAME})         
    """

    private static let resourceAssetColorExtensionTemplate = """
    public extension UIColor {
        enum {EXT_NAME} {
            {COLOR_GETTERS}
        }
    }            
    """

    private static let resourceAssetColorGetterTemplate = """
    public static let {VAR_NAME}: UIColor = .init(resource: .{VAR_NAME})         
    """
}
