//
//  GenerateResources.swift
//  Copyright © 2025 Jason Fieldman.
//

import ArgumentParser
import DependencyMagnetLib
import Foundation
import InternalUtilities
import ModuleManagementLib
import ProjectSpec
import XcodeProj
import Yams

public struct GenerateResourcesOptions {
    public let modulesPath: String
    public let packageFileName: String

    public init(
        modulesPath: String,
        packageFileName: String
    ) {
        self.modulesPath = modulesPath
        self.packageFileName = packageFileName
    }
}

public enum GenerateResources {
    public static func execute(with options: GenerateResourcesOptions) throws {
        let absoluteModuleBasePath = options.modulesPath.prependingCurrentDirectory()
        let absoluteProjectPath = FileManager.default.currentDirectoryPath

        // Verify root path exists
        guard FileManager.default.directoryExists(atPath: absoluteModuleBasePath) else {
            try throwError(.pathNotFound, "Module directory not found at path: \(options.modulesPath)")
        }

        let packages = ModulePackageManager.packages(
            named: options.packageFileName,
            root: options.modulesPath,
            absoluteProjectPath: absoluteProjectPath
        )

        guard packages.count > 0 else {
            vprint(.normal, "No packages found at root path: \(options.modulesPath)")
            return
        }

        // Parse injections
        for package in packages {
            guard let resourceModule = package.modules[.resources] else {
                continue
            }

            try resourceModule.generateBundleExtension()
        }
    }
}

private extension Module {
    func generateBundleExtension() throws {
        let bundleResourceExtensionPath = projectBasePath.appendingMissingSlash() + "Bundle+\(name).swift"

        // Create bundle extension for resource-containing modules
        try Module.bundleResourceExtensionTemplate
            .replacingOccurrences(of: "{MODULE_NAME}", with: name)
            .write(toFile: bundleResourceExtensionPath, atomically: true, encoding: .utf8)
    }

    private static let bundleResourceExtensionTemplate = """
    import Foundation

    // This file is autogenerated by Velocity to provide a way to programmatically
    // access this Bundle

    public extension Bundle {
        /// Access the {MODULE_NAME} bundle 
        static let {MODULE_NAME} = Bundle(for: {MODULE_NAME}Beacon.self)
        private class {MODULE_NAME}Beacon {}
    }
    """
}
