//
//  GenerateResources.swift
//  Copyright © 2025 Jason Fieldman.
//

import ArgumentParser
import DependencyMagnetLib
import Foundation
import InternalUtilities
import ModuleManagementLib
import ProjectSpec
import XcodeProj
import Yams

public struct GenerateResourcesOptions {
    public let modulesPath: String
    public let packageFileName: String
    public let noSwiftUiAssets: Bool

    public init(
        modulesPath: String,
        packageFileName: String,
        noSwiftUiAssets: Bool,
    ) {
        self.modulesPath = modulesPath
        self.packageFileName = packageFileName
        self.noSwiftUiAssets = noSwiftUiAssets
    }
}

public enum GenerateResources {
    public static func execute(with options: GenerateResourcesOptions) throws {
        let absoluteModuleBasePath = options.modulesPath.prependingCurrentDirectory()
        let absoluteProjectPath = FileManager.default.currentDirectoryPath

        // Verify root path exists
        guard FileManager.default.directoryExists(atPath: absoluteModuleBasePath) else {
            try throwError(.pathNotFound, "Module directory not found at path: \(options.modulesPath)")
        }

        let packages = ModulePackageManager.packages(
            named: options.packageFileName,
            root: options.modulesPath,
            absoluteProjectPath: absoluteProjectPath
        )

        guard packages.count > 0 else {
            vprint(.normal, "No packages found at root path: \(options.modulesPath)")
            return
        }

        // Parse injections
        for package in packages {
            guard let resourceModule = package.modules[.resources] else {
                continue
            }

            try resourceModule.generateBundleExtension()
            try resourceModule.generateAssetExtensions(noSwiftUiAssets: options.noSwiftUiAssets)
            try resourceModule.generateStringExtensions()
        }
    }
}

private extension Module {
    func generateBundleExtension() throws {
        let bundleResourceExtensionPath = projectBasePath.appendingMissingSlash() + "Bundle+\(name).swift"

        // Create bundle extension for resource-containing modules
        try Module.bundleResourceExtensionTemplate
            .replacingOccurrences(of: "{MODULE_NAME}", with: name)
            .write(toFile: bundleResourceExtensionPath, atomically: true, encoding: .utf8)
    }

    private static let bundleResourceExtensionTemplate = """
    import Foundation

    // This file is autogenerated by Velocity to provide a way to programmatically
    // access this Bundle

    public extension Bundle {
        /// Access the {MODULE_NAME} bundle 
        static let {MODULE_NAME} = Bundle(for: {MODULE_NAME}Beacon.self)
        private class {MODULE_NAME}Beacon {}
    }
    """
}

private extension Module {
    func generateAssetExtensions(noSwiftUiAssets: Bool) throws {
        try FileManager.default.files(at: projectBasePath, matching: { $0.hasSuffix(".xcassets") }).forEach { xcassetsPath in
            let assetPackName = xcassetsPath.lastPathComponent.removingSuffix(".xcassets")

            let colorSets = FileManager.default.files(at: xcassetsPath, matching: { $0.hasSuffix(".colorset") })
                .map { $0.lastPathComponent.removingSuffix(".colorset") }

            let imageSets = FileManager.default.files(at: xcassetsPath, matching: { $0.hasSuffix(".imageset") })
                .map { $0.lastPathComponent.removingSuffix(".imageset") }

            guard colorSets.count > 0 || imageSets.count > 0 else {
                return
            }

            vprint(.verbose, "Generating extensions for \(name): \(xcassetsPath).xcassets")

            var colorTemplateContent = ""
            if colorSets.count > 0 {
                colorTemplateContent = Module.resourceAssetColorExtensionTemplate
                    .replacingOccurrences(of: "{EXT_NAME}", with: assetPackName)
                    .replacingOccurrences(
                        of: "{COLOR_GETTERS}",
                        with: colorSets.map {
                            Module.resourceAssetColorGetterTemplate
                                .replacingOccurrences(of: "{VAR_NAME}", with: $0.lowercaseFirstLetter())
                        }.joined(separator: "\n")
                    )
            }

            var swiftUIColorTemplateContent = ""
            if colorSets.count > 0 {
                swiftUIColorTemplateContent = Module.resourceAssetSwiftUIColorExtensionTemplate
                    .replacingOccurrences(of: "{EXT_NAME}", with: assetPackName)
                    .replacingOccurrences(
                        of: "{COLOR_GETTERS}",
                        with: colorSets.map {
                            Module.resourceAssetSwiftUIColorGetterTemplate
                                .replacingOccurrences(of: "{VAR_NAME}", with: $0.lowercaseFirstLetter())
                        }.joined(separator: "\n")
                    )
            }

            if !noSwiftUiAssets, swiftUIColorTemplateContent.count > 0 {
                colorTemplateContent.append("\n\n")
                colorTemplateContent.append(swiftUIColorTemplateContent)
            }

            var imageTemplateContent = ""
            if imageSets.count > 0 {
                imageTemplateContent = Module.resourceAssetImageExtensionTemplate
                    .replacingOccurrences(of: "{EXT_NAME}", with: assetPackName)
                    .replacingOccurrences(
                        of: "{IMAGE_GETTERS}",
                        with: imageSets.map {
                            Module.resourceAssetImageGetterTemplate
                                .replacingOccurrences(of: "{VAR_NAME}", with: $0.lowercaseFirstLetter())
                        }.joined(separator: "\n")
                    )
            }

            var swiftUIImageTemplateContent = ""
            if imageSets.count > 0 {
                swiftUIImageTemplateContent = Module.resourceAssetSwiftUIImageExtensionTemplate
                    .replacingOccurrences(of: "{EXT_NAME}", with: assetPackName)
                    .replacingOccurrences(
                        of: "{IMAGE_GETTERS}",
                        with: imageSets.map {
                            Module.resourceAssetSwiftUIImageGetterTemplate
                                .replacingOccurrences(of: "{VAR_NAME}", with: $0.lowercaseFirstLetter())
                        }.joined(separator: "\n")
                    )
            }

            if !noSwiftUiAssets, swiftUIImageTemplateContent.count > 0 {
                imageTemplateContent.append("\n\n")
                imageTemplateContent.append(swiftUIImageTemplateContent)
            }

            try Module.resourceAssetExtensionTemplate
                .replacingOccurrences(of: "{IMPORT_SWIFTUI}", with: noSwiftUiAssets ? "" : "\nimport SwiftUI")
                .replacingOccurrences(of: "{UICOLOR_EXT}", with: colorTemplateContent)
                .replacingOccurrences(of: "{UIIMAGE_EXT}", with: imageTemplateContent)
                .write(toFile: projectBasePath.appendingMissingSlash() + "\(assetPackName)+Assets.swift", atomically: true, encoding: .utf8)
        }
    }

    private static let resourceAssetExtensionTemplate = """
    import UIKit{IMPORT_SWIFTUI}

    // This file is autogenerated by Velocity to provide a way to programmatically
    // access this Bundle's assets

    {UIIMAGE_EXT}

    {UICOLOR_EXT}
    """

    private static let resourceAssetImageExtensionTemplate = """
    public extension UIImage {
        enum {EXT_NAME} {
            {IMAGE_GETTERS}
        }
    }            
    """

    private static let resourceAssetImageGetterTemplate = """
    public static let {VAR_NAME}: UIImage = .init(resource: .{VAR_NAME})         
    """

    private static let resourceAssetSwiftUIImageExtensionTemplate = """
    public extension Image {
        enum {EXT_NAME} {
            {IMAGE_GETTERS}
        }
    }            
    """

    private static let resourceAssetSwiftUIImageGetterTemplate = """
    public static let {VAR_NAME}: Image = .init(uiImage: .{VAR_NAME})         
    """

    private static let resourceAssetColorExtensionTemplate = """
    public extension UIColor {
        enum {EXT_NAME} {
            {COLOR_GETTERS}
        }
    }            
    """

    private static let resourceAssetColorGetterTemplate = """
    public static let {VAR_NAME}: UIColor = .init(resource: .{VAR_NAME})         
    """

    private static let resourceAssetSwiftUIColorExtensionTemplate = """
    public extension Color {
        enum {EXT_NAME} {
            {COLOR_GETTERS}
        }
    }            
    """

    private static let resourceAssetSwiftUIColorGetterTemplate = """
    public static let {VAR_NAME}: Color = .init(UIColor.{EXT_NAME}.{VAR_NAME})         
    """
}

private extension Module {
    func generateStringExtensions() throws {
        struct KeyValuePair {
            let key: String
            let value: String
            let formatSpecifiers: [FormatSpecifierType]
        }

        let basePath = projectBasePath.appendingMissingSlash() + "Base.lproj"
        try FileManager.default.files(at: basePath, matching: { $0.hasSuffix(".strings") }).forEach { stringsFile in
            let stringsFileSlug = stringsFile.lastPathComponent.removingSuffix(".strings")
            vprint(.verbose, "Generating extensions for \(name): \(stringsFileSlug).strings")

            let lineReader = LineReader(path: stringsFile)!
            let pairs: [KeyValuePair] = try lineReader.compactMap { line -> KeyValuePair? in
                guard line.hasPrefix("\"") else { return nil }
                let components = line.trimmingCharacters(in: .whitespacesAndNewlines).components(separatedBy: "\" = \"")
                guard components.count == 2 else { return nil }
                if !components[1].hasSuffix("\";") {
                    vprint(.error, "Invalid format for \(stringsFileSlug).strings: a line is not terminated with a semicolon.")
                }
                return try KeyValuePair(
                    key: String(components[0].dropFirst()).replacingOccurrences(of: ".", with: "_"),
                    value: String(components[1].dropLast(2)),
                    formatSpecifiers: formatSpecifierTypes(for: String(components[1].dropLast(2)))
                )
            }

            guard !pairs.isEmpty else { return }

            let stringFuncs: [String] = pairs.sorted(by: { $0.key.lowercased() < $1.key.lowercased() }).map { pair -> String in
                if pair.formatSpecifiers.isEmpty {
                    return Module.stringFuncTemplateNoParams
                        .replacingOccurrences(of: "{ORIGINAL_STRING}", with: pair.value)
                        .replacingOccurrences(of: "{VAR_NAME}", with: pair.key.camelCased())
                        .replacingOccurrences(of: "{KEY}", with: pair.key)
                        .replacingOccurrences(of: "{DEFAULT}", with: pair.value)
                        .replacingOccurrences(of: "{TABLE}", with: stringsFileSlug)
                        .replacingOccurrences(of: "{BUNDLE_NAME}", with: name)
                } else {
                    let funcParams = pair.formatSpecifiers.enumerated().map { i, specifier in
                        "_ arg\(i): \(specifier.rawValue)"
                    }.joined(separator: ", ")

                    let formatParams = pair.formatSpecifiers.enumerated().map { i, _ in
                        "arg\(i)"
                    }.joined(separator: ", ")

                    return Module.stringFuncTemplateWithParams
                        .replacingOccurrences(of: "{ORIGINAL_STRING}", with: pair.value)
                        .replacingOccurrences(of: "{FUNC_NAME}", with: pair.key.camelCased())
                        .replacingOccurrences(of: "{FUNC_PARAMS}", with: funcParams)
                        .replacingOccurrences(of: "{FORMAT_PARAMS}", with: formatParams)
                        .replacingOccurrences(of: "{KEY}", with: pair.key)
                        .replacingOccurrences(of: "{DEFAULT}", with: pair.value)
                        .replacingOccurrences(of: "{TABLE}", with: stringsFileSlug)
                        .replacingOccurrences(of: "{BUNDLE_NAME}", with: name)
                }
            }

            try Module.stringsExtensionTemplate
                .replacingOccurrences(of: "{EXT_NAME}", with: stringsFileSlug)
                .replacingOccurrences(of: "{STRING_FUNCS}", with: stringFuncs.joined(separator: "\n"))
                .write(toFile: projectBasePath.appendingMissingSlash() + "\(stringsFileSlug)+Strings.swift", atomically: true, encoding: .utf8)
        }
    }

    private static let stringsExtensionTemplate: String = """
    import Foundation

    // This file is autogenerated by Velocity to provide a way to programmatically
    // access this Bundle's strings

    public extension String {
        enum {EXT_NAME} {
            {STRING_FUNCS}
        }
    }    
    """

    private static let stringFuncTemplateNoParams: String = """

    /// "{ORIGINAL_STRING}"
    public static let {VAR_NAME}: String = .init(localized: "{KEY}", defaultValue: "{DEFAULT}", table: "{TABLE}", bundle: .{BUNDLE_NAME})
    """

    private static let stringFuncTemplateWithParams: String = """

    /// "{ORIGINAL_STRING}"
    public static func {FUNC_NAME}({FUNC_PARAMS}) -> String {
        let str = String(localized: "{KEY}", defaultValue: "{DEFAULT}", table: "{TABLE}", bundle: .{BUNDLE_NAME})
        return String(format: str, arguments: [{FORMAT_PARAMS}])
    }    
    """

    enum FormatSpecifierType: String {
        case string = "String"
        case int = "Int"
        case float = "Float"
    }

    func formatSpecifierTypes(for string: String) throws -> [FormatSpecifierType] {
        try extractSpecifiers(
            from: string,
            with: NSRegularExpression(pattern: #"%[^% ]*?([@dsfi])"#, options: [])
        ).compactMap { convertSpecifier(toType: $0) }
    }

    private func extractSpecifiers(from string: String, with regex: NSRegularExpression) -> [String] {
        var matches: [String] = []

        regex.enumerateMatches(
            in: string,
            options: [],
            range: NSRange(string.startIndex ..< string.endIndex, in: string)
        ) { match, _, _ in
            guard let match,
                  let matchRange = Range(match.range(at: 1), in: string)
            else {
                return
            }

            let matchText = String(string[matchRange])
            matches.append(matchText)
        }

        return matches
    }

    private func convertSpecifier(toType specifier: String) -> FormatSpecifierType? {
        switch specifier {
        case "@", "s":
            .string
        case "f":
            .float
        case "d", "i":
            .int
        default:
            nil
        }
    }
}
