//
//  Bundle+ResourceExtension.swift
//  Copyright © 2025 Jason Fieldman.
//

import Foundation

// This file is autogenerated by Velocity to provide a way to programmatically
// access this Bundle

public extension Bundle {
    /// Access the StringsResources bundle
    static let StringsResources = Bundle(for: StringsResourcesBeacon.self)
    private class StringsResourcesBeacon {}
}
