//
//  Strings.swift
//  Copyright © 2025 Jason Fieldman.
//

import Foundation

// This file is autogenerated by Velocity to provide a way to programmatically
// access this Bundle's strings

public extension String {
    enum Strings {
        /// "Coaster Pal"
        public static let coasterPal: String = .init(localized: "coaster_pal", defaultValue: "Coaster Pal", table: "Strings", bundle: .StringsResources)

        /// "Parks"
        public static let parksNavigationTitle: String = .init(localized: "parks_navigation_title", defaultValue: "Parks", table: "Strings", bundle: .StringsResources)
    }
}
